-- =============================================================
-- properties.lua -- Win PC Control
--
-- Defines all user-configurable properties that appear in the
-- plugin's Properties panel in Q-SYS Designer.
--
-- Property types: "string", "integer", "boolean", "enum"
-- Properties are read at runtime via Properties["Name"].Value
-- =============================================================


-- -------------------------------------------------------------
-- IDENTITY
-- Friendly name for the controlled PC. Shown on the block face
-- in the schematic. Does not affect network connectivity.
-- -------------------------------------------------------------
table.insert(props, {
  Name  = "Computer Name",
  Type  = "string",
  Value = ""
})


-- -------------------------------------------------------------
-- NETWORK
-- Hostname or IP address of the Windows PC running the server.
-- Hostname is preferred -- it stays valid even if the IP changes
-- (assuming DNS or mDNS resolution is available on the network).
-- Example: "studio-pc.local" or "192.168.1.50"
-- -------------------------------------------------------------
table.insert(props, {
  Name  = "Hostname or IP",
  Type  = "string",
  Value = ""
})

-- MAC address used for Wake-on-LAN.
-- This field is OPTIONAL. If left blank, the MAC will be
-- auto-discovered the first time the PC is polled successfully
-- (the server reports it in every /status response).
-- Only required if you need to WOL the PC before it has ever
-- been seen online by this plugin instance.
-- Format: "AA:BB:CC:DD:EE:FF" or "AA-BB-CC-DD-EE-FF"
table.insert(props, {
  Name  = "MAC Address",
  Type  = "string",
  Value = ""
})


-- -------------------------------------------------------------
-- HTTP SERVER SETTINGS
-- Must match what was configured on the PC during install.ps1.
-- The token is generated by install.ps1 and stored in
-- C:\QSYS WinPC Control\config.txt on the Windows PC.
-- -------------------------------------------------------------
table.insert(props, {
  Name  = "HTTP Port",
  Type  = "integer",
  Min   = 1024,
  Max   = 65535,
  Value = 2207     -- Default port chosen to avoid IANA conflicts
})

table.insert(props, {
  Name  = "Auth Token",
  Type  = "string",
  Value = ""
})


-- -------------------------------------------------------------
-- POLLING
-- How often (in seconds) to send GET /status to check if the
-- PC is online and to sync volume/mute back to Q-SYS.
-- Shorter interval = faster status updates but more traffic.
-- 30 seconds is a reasonable default for most installs.
-- -------------------------------------------------------------
table.insert(props, {
  Name  = "Poll Interval (s)",
  Type  = "integer",
  Min   = 5,
  Max   = 300,
  Value = 15
})





